# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


sampleText01 = "consectetur adipiscing elit. Nulla nec ante scelerisque, imperdiet tellus vitae, tincidunt diam. Vestibulum urna diam, congue vitae rutrum a, porttitor eu velit. Donec gravida massa nisl, quis sollicitudin velit mollis eget. Donec vel odio mauris. Maecenas bibendum consectetur neque, ut efficitur purus sodales vitae. Sed leo nulla, lobortis ac arcu id, fermentum blandit felis. Proin sit amet nulla ut mauris dictum fermentum.
Aliquam dapibus sit amet odio at consectetur. Nulla facilisi. Suspendisse semper dapibus lobortis. Aliquam vestibulum, nibh in accumsan bibendum, justo dolor porta urna, ac tincidunt nisi arcu vitae ex. Morbi dignissim, est sed vulputate hendrerit, lectus nibh convallis tortor, sit amet ornare nunc dui a lectus. Etiam et nibh eget urna venenatis vehicula. Curabitur accumsan ullamcorper erat nec aliquet. Proin congue nunc eu erat blandit, sit amet auctor nunc tristique. Aenean sit amet elit et odio accumsan imperdiet non eu enim.
Maecenas ac urna tempus, ullamcorper neque et, varius erat. Proin semper libero quis mauris sollicitudin, tincidunt blandit risus luctus. Quisque pellentesque massa non nulla hendrerit porta. Quisque placerat ante turpis, vitae viverra leo luctus non. Vestibulum elit ante, hendrerit sit amet elementum quis, egestas a quam. Maecenas condimentum dolor nulla, non accumsan elit mattis ut. Ut eget massa sapien. Nulla lorem sapien, rutrum ac augue vitae, suscipit interdum mi. Proin odio metus, vestibulum et nibh et, placerat dictum lectus.
Praesent nunc purus, maximus rutrum blandit et, ultricies at nibh. Donec dignissim velit sed metus hendrerit, non posuere lorem sodales. In non tellus quam. Phasellus sed molestie lectus. Integer sit amet pulvinar justo, in tristique dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. In blandit neque tortor, sed fermentum ipsum vulputate eu. Maecenas rhoncus turpis ac lectus suscipit, eget pharetra dui aliquet. Maecenas sollicitudin quam quis lorem aliquet, ut tristique mauris finibus. Fusce gravida ante commodo turpis efficitur lobortis sed at enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis at aliquam ex. Duis eu elit diam. Cras vel dui nisi. Pellentesque congue eleifend lacus, at consequat velit efficitur ut. Sed nec egestas nisl.
Praesent dolor massa, mattis a aliquet sit amet, facilisis eu diam. Suspendisse neque dolor, volutpat quis purus ac, aliquam mollis neque. Cras bibendum, nisi sit amet condimentum elementum, erat nulla lacinia ligula, in suscipit nisl leo a enim. Mauris rutrum, mauris vitae dapibus mollis, risus neque elementum ex, sed posuere lectus sem non orci. Pellentesque sed lacus arcu. Sed tincidunt ultrices augue, ut porta tellus hendrerit ac. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi vel ante semper, malesuada justo ut, sodales justo. Mauris eleifend enim metus, mollis pellentesque sapien convallis dapibus. Pellentesque sagittis magna ac viverra elementum. Curabitur eget metus et ligula ullamcorper euismod eu ut diam. Donec et tempus purus. Nunc augue enim, sagittis vitae dolor a, semper congue tellus. Maecenas sollicitudin eleifend quam, quis sodales augue gravida eget."

sampleText02 = "Nulla facilisi. Suspendisse semper dapibus lobortis. Aliquam vestibulum, nibh in accumsan bibendum, justo dolor porta urna, ac tincidunt nisi arcu vitae ex. Morbi dignissim, est sed vulputate hendrerit, lectus nibh convallis tortor, sit amet ornare nunc dui a lectus. Etiam et nibh eget urna venenatis vehicula. Curabitur accumsan ullamcorper erat nec aliquet. Proin congue nunc eu erat blandit, sit amet auctor nunc tristique. Aenean sit amet elit et odio accumsan imperdiet non eu enim.
Maecenas ac urna tempus, ullamcorper neque et, varius erat. Proin semper libero quis mauris sollicitudin, tincidunt blandit risus luctus. Quisque pellentesque massa non nulla hendrerit porta. Quisque placerat ante turpis, vitae viverra leo luctus non. Vestibulum elit ante, hendrerit sit amet elementum quis, egestas a quam. Maecenas condimentum dolor nulla, non accumsan elit mattis ut. Ut eget massa sapien. Nulla lorem sapien, rutrum ac augue vitae, suscipit interdum mi. Proin odio metus, vestibulum et nibh et, placerat dictum lectus.
Praesent nunc purus, maximus rutrum blandit et, ultricies at nibh. Donec dignissim velit sed metus hendrerit, non posuere lorem sodales. In non tellus quam. Phasellus sed molestie lectus. Integer sit amet pulvinar justo, in tristique dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. In blandit neque tortor, sed fermentum ipsum vulputate eu. Maecenas rhoncus turpis ac lectus suscipit, eget pharetra dui aliquet. Maecenas sollicitudin quam quis lorem aliquet, ut tristique mauris finibus. Fusce gravida ante commodo turpis efficitur lobortis sed at enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis at aliquam ex. Duis eu elit diam. Cras vel dui nisi. Pellentesque congue eleifend lacus, at consequat velit efficitur ut. Sed nec egestas nisl.
Praesent dolor massa, mattis a aliquet sit amet, facilisis eu diam. Suspendisse neque dolor, volutpat quis purus ac, aliquam mollis neque. Cras bibendum, nisi sit amet condimentum elementum, erat nulla lacinia ligula, in suscipit nisl leo a enim. Mauris rutrum, mauris vitae dapibus mollis, risus neque elementum ex, sed posuere lectus sem non orci. Pellentesque sed lacus arcu. Sed tincidunt ultrices augue, ut porta tellus hendrerit ac. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi vel ante semper, malesuada justo ut, sodales justo. Mauris eleifend enim metus, mollis pellentesque sapien convallis dapibus. Pellentesque sagittis magna ac viverra elementum. Curabitur eget metus et ligula ullamcorper euismod eu ut diam. Donec et tempus purus. Nunc augue enim, sagittis vitae dolor a, semper congue tellus. Maecenas sollicitudin eleifend quam, quis sodales augue gravida eget."

sampleText03 = "ullamcorper neque et, varius erat. Proin semper libero quis mauris sollicitudin, tincidunt blandit risus luctus. Quisque pellentesque massa non nulla hendrerit porta. Quisque placerat ante turpis, vitae viverra leo luctus non. Vestibulum elit ante, hendrerit sit amet elementum quis, egestas a quam. Maecenas condimentum dolor nulla, non accumsan elit mattis ut. Ut eget massa sapien. Nulla lorem sapien, rutrum ac augue vitae, suscipit interdum mi. Proin odio metus, vestibulum et nibh et, placerat dictum lectus.
Praesent nunc purus, maximus rutrum blandit et, ultricies at nibh. Donec dignissim velit sed metus hendrerit, non posuere lorem sodales. In non tellus quam. Phasellus sed molestie lectus. Integer sit amet pulvinar justo, in tristique dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. In blandit neque tortor, sed fermentum ipsum vulputate eu. Maecenas rhoncus turpis ac lectus suscipit, eget pharetra dui aliquet. Maecenas sollicitudin quam quis lorem aliquet, ut tristique mauris finibus. Fusce gravida ante commodo turpis efficitur lobortis sed at enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis at aliquam ex. Duis eu elit diam. Cras vel dui nisi. Pellentesque congue eleifend lacus, at consequat velit efficitur ut. Sed nec egestas nisl.
Praesent dolor massa, mattis a aliquet sit amet, facilisis eu diam. Suspendisse neque dolor, volutpat quis purus ac, aliquam mollis neque. Cras bibendum, nisi sit amet condimentum elementum, erat nulla lacinia ligula, in suscipit nisl leo a enim. Mauris rutrum, mauris vitae dapibus mollis, risus neque elementum ex, sed posuere lectus sem non orci. Pellentesque sed lacus arcu. Sed tincidunt ultrices augue, ut porta tellus hendrerit ac. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi vel ante semper, malesuada justo ut, sodales justo. Mauris eleifend enim metus, mollis pellentesque sapien convallis dapibus. Pellentesque sagittis magna ac viverra elementum. Curabitur eget metus et ligula ullamcorper euismod eu ut diam. Donec et tempus purus. Nunc augue enim, sagittis vitae dolor a, semper congue tellus. Maecenas sollicitudin eleifend quam, quis sodales augue gravida eget."

sampleText04 = "maximus rutrum blandit et, ultricies at nibh. Donec dignissim velit sed metus hendrerit, non posuere lorem sodales. In non tellus quam. Phasellus sed molestie lectus. Integer sit amet pulvinar justo, in tristique dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. In blandit neque tortor, sed fermentum ipsum vulputate eu. Maecenas rhoncus turpis ac lectus suscipit, eget pharetra dui aliquet. Maecenas sollicitudin quam quis lorem aliquet, ut tristique mauris finibus. Fusce gravida ante commodo turpis efficitur lobortis sed at enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis at aliquam ex. Duis eu elit diam. Cras vel dui nisi. Pellentesque congue eleifend lacus, at consequat velit efficitur ut. Sed nec egestas nisl.
Praesent dolor massa, mattis a aliquet sit amet, facilisis eu diam. Suspendisse neque dolor, volutpat quis purus ac, aliquam mollis neque. Cras bibendum, nisi sit amet condimentum elementum, erat nulla lacinia ligula, in suscipit nisl leo a enim. Mauris rutrum, mauris vitae dapibus mollis, risus neque elementum ex, sed posuere lectus sem non orci. Pellentesque sed lacus arcu. Sed tincidunt ultrices augue, ut porta tellus hendrerit ac. Aliquam erat volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi vel ante semper, malesuada justo ut, sodales justo. Mauris eleifend enim metus, mollis pellentesque sapien convallis dapibus. Pellentesque sagittis magna ac viverra elementum. Curabitur eget metus et ligula ullamcorper euismod eu ut diam. Donec et tempus purus. Nunc augue enim, sagittis vitae dolor a, semper congue tellus. Maecenas sollicitudin eleifend quam, quis sodales augue gravida eget."


postArray = [
  {title: "Lorem ipsum dolor sit amet", message: sampleText01},
  {title: "Aliquam dapibus sit amet", message: sampleText02},
  {title: "Maecenas ac urna tempus", message: sampleText03},
  {title: "Praesent nunc purus", message: sampleText04}
]

Post.create(postArray);
